// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:number,arg12:number,arg13:string,arg14:number):Promise<void>;

export function BackupToProvider(arg1:string,arg2:string):Promise<void>;

export function BackupToWebDAV(arg1:string):Promise<void>;

export function CleanupInteractions(arg1:number):Promise<string>;

export function ClearCache():Promise<void>;

export function ClearLogs():Promise<void>;

export function DeleteArchive(arg1:string):Promise<string>;

export function DeleteBackups(arg1:string,arg2:Array<string>):Promise<void>;

export function DeleteWebDAVBackups(arg1:Array<string>):Promise<void>;

export function DetectBackupConflict(arg1:string,arg2:string):Promise<string>;

export function DetectWebDAVConflict(arg1:string):Promise<string>;

export function ExportAllEndpoints(arg1:boolean):Promise<string>;

export function ExportEndpoints(arg1:string,arg2:boolean):Promise<string>;

export function ExportInteractions(arg1:string):Promise<string>;

export function FetchBroadcast(arg1:string):Promise<string>;

export function FetchImageAsBase64(arg1:string):Promise<string>;

export function FetchModels(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateMockArchives(arg1:number):Promise<string>;

export function GetActiveRequests():Promise<string>;

export function GetAlertConfig():Promise<string>;

export function GetAllEndpointTags():Promise<Array<string>>;

export function GetArchiveData(arg1:string):Promise<string>;

export function GetArchiveTrend(arg1:string):Promise<string>;

export function GetAutoDarkTheme():Promise<string>;

export function GetAutoLightTheme():Promise<string>;

export function GetAutoThemeMode():Promise<string>;

export function GetCacheConfig():Promise<string>;

export function GetCacheStats():Promise<string>;

export function GetChangelog(arg1:string):Promise<string>;

export function GetConfig():Promise<string>;

export function GetConnectedClients(arg1:number):Promise<string>;

export function GetCostByPeriod(arg1:string):Promise<string>;

export function GetCostDaily():Promise<string>;

export function GetCostMonthly():Promise<string>;

export function GetCostTrend(arg1:string):Promise<string>;

export function GetCostWeekly():Promise<string>;

export function GetCostYesterday():Promise<string>;

export function GetCurrentEndpoint(arg1:string):Promise<string>;

export function GetDailyRequestDetails(arg1:number,arg2:number):Promise<string>;

export function GetEndpointCheckResults():Promise<string>;

export function GetEndpointHealth():Promise<string>;

export function GetEndpointMetrics():Promise<string>;

export function GetHealthCheckInterval():Promise<number>;

export function GetHealthHistory(arg1:string,arg2:string,arg3:number):Promise<Array<Record<string, any>>>;

export function GetHealthHistoryRetentionDays():Promise<number>;

export function GetInteractionDates():Promise<string>;

export function GetInteractionDetail(arg1:string,arg2:string):Promise<string>;

export function GetInteractionEnabled():Promise<string>;

export function GetInteractionStoragePath():Promise<string>;

export function GetInteractions(arg1:string):Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLogLevel():Promise<number>;

export function GetLogs():Promise<string>;

export function GetLogsByLevel(arg1:number):Promise<string>;

export function GetMonitorSnapshot():Promise<string>;

export function GetPerformanceStats(arg1:string):Promise<string>;

export function GetPricingInfo():Promise<string>;

export function GetProxyURL():Promise<string>;

export function GetQuotaStatus(arg1:string,arg2:string):Promise<string>;

export function GetQuotaStatuses(arg1:string):Promise<string>;

export function GetRateLimitConfig():Promise<string>;

export function GetRateLimitStats():Promise<string>;

export function GetRecentRequests(arg1:number):Promise<string>;

export function GetRequestTimeout():Promise<number>;

export function GetRoutingConfig():Promise<string>;

export function GetStats():Promise<string>;

export function GetStatsDaily():Promise<string>;

export function GetStatsMonthly():Promise<string>;

export function GetStatsTrend():Promise<string>;

export function GetStatsTrendByPeriod(arg1:string):Promise<string>;

export function GetStatsWeekly():Promise<string>;

export function GetStatsYesterday():Promise<string>;

export function GetSystemLanguage():Promise<string>;

export function GetTheme():Promise<string>;

export function GetThemeAuto():Promise<boolean>;

export function GetTokenTrendData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function ImportEndpoints(arg1:string,arg2:string):Promise<string>;

export function ListArchives():Promise<string>;

export function ListBackups(arg1:string):Promise<string>;

export function ListWebDAVBackups():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RemoveEndpoint(arg1:string,arg2:number):Promise<void>;

export function ReorderEndpoints(arg1:string,arg2:Array<string>):Promise<void>;

export function ResetMonitorMetrics():Promise<void>;

export function ResetQuota(arg1:string,arg2:string):Promise<void>;

export function ResetRateLimitStats():Promise<void>;

export function RestoreFromProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreFromWebDAV(arg1:string,arg2:string):Promise<void>;

export function SetAlertConfig(arg1:boolean,arg2:number,arg3:boolean,arg4:boolean,arg5:number,arg6:boolean,arg7:number,arg8:number):Promise<void>;

export function SetAutoDarkTheme(arg1:string):Promise<void>;

export function SetAutoLightTheme(arg1:string):Promise<void>;

export function SetAutoThemeMode(arg1:string):Promise<void>;

export function SetCacheConfig(arg1:boolean,arg2:number,arg3:number):Promise<void>;

export function SetCloseWindowBehavior(arg1:string):Promise<void>;

export function SetHealthCheckInterval(arg1:number):Promise<void>;

export function SetHealthHistoryRetentionDays(arg1:number):Promise<void>;

export function SetInteractionEnabled(arg1:boolean):Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLogLevel(arg1:number):Promise<void>;

export function SetProxyURL(arg1:string):Promise<void>;

export function SetRateLimitConfig(arg1:boolean,arg2:number,arg3:number):Promise<void>;

export function SetRequestTimeout(arg1:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetThemeAuto(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function SwitchToEndpoint(arg1:string,arg2:string):Promise<void>;

export function TestAllEndpointsAndOptimize(arg1:string):Promise<string>;

export function TestAllEndpointsZeroCost(arg1:string):Promise<string>;

export function TestEndpoint(arg1:string,arg2:number):Promise<string>;

export function TestEndpointLight(arg1:string,arg2:number):Promise<string>;

export function TestS3Connection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:boolean):Promise<string>;

export function TestWebDAVConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleEndpoint(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function UpdateBackupProvider(arg1:string):Promise<void>;

export function UpdateConfig(arg1:string):Promise<void>;

export function UpdateEndpoint(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:number,arg12:number,arg13:number,arg14:string,arg15:number):Promise<void>;

export function UpdateLocalBackupDir(arg1:string):Promise<void>;

export function UpdatePort(arg1:number):Promise<void>;

export function UpdateRoutingConfig(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string):Promise<void>;

export function UpdateS3BackupConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:boolean):Promise<void>;

export function UpdateWebDAVConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
